### PR TITLE
`io_app` used dynamically

### PR DESCRIPTION
**Pull request by larshp**
set needed, https://rules.abaplint.org/unused_variables/

### CODE REVIEW

**Comment by oblomov-dev** [comment]
i set the severity of abaplint checks only down to warning all the time, but forgot that pragmas are also helpful. thanks for the hint!

**Comment by larshp** [comment]
you want to keep main completely clean, or else which rules should be respected?

if I want to contribute something, first thing is that I have to clean up the code, it should not be that way

**Comment by larshp** [comment]
exactly

on warnings: the severity is mainly a feature because it is part of code inspector

but, if there is a warning, the developer will not know if it is something that is to be enforced or not. Ie. better to have it required, or disable the rule.

**Comment by oblomov-dev** [comment]
ah ok, good to know. so warning is more something from the SAP and atc check world but in a serious ci/cd process it is not really useful. ok i am learning and will keep this in mind :)

**Pull request merged**
